name: Release Obsidian plugin

on:
  push:
    tags:
      - "v*.*.*"

env:
  PLUGIN_NAME: obsidian-plugin-camille # Change this to match the id of your plugin.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Build and create zip file
        id: build
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          artifacts: |
            ${{ env.PLUGIN_NAME }}.zip
          artifactContentType: application/zip
          allowUpdates: true
          draft: false
          prerelease: false